// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnj0AjequQZY-eAIIyElNFc8OwWPQkkVw',
    appId: '1:534364307070:android:30777978b1569fbe3e222f',
    messagingSenderId: '534364307070',
    projectId: 'drb-sa',
    databaseURL: 'https://drb-sa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drb-sa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYujFxuvyGKz3svHElMbYr5JyU_ROj6y8',
    appId: '1:534364307070:ios:38022ddb6c6ca27b3e222f',
    messagingSenderId: '534364307070',
    projectId: 'drb-sa',
    databaseURL: 'https://drb-sa-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drb-sa.firebasestorage.app',
    androidClientId: '534364307070-512m9ahlcr39gp235hq0oid7h2r1f1nu.apps.googleusercontent.com',
    iosClientId: '534364307070-l4c1c9oshbv40t1br30at3vmcvg0va3u.apps.googleusercontent.com',
    iosBundleId: 'com.t8nat.drbrider',
  );

}